# Data Description
- Author: KUO, PING-FENG
- Date first created: 2025-10-14
- Background: 簡述資料內容
- Unit of observation: 3993
- Sample period: 2002-2024
- Known issues:  2015的人口資料遺失、某些縣市的測站資料需要再補充
- Definition for each variable: 
    - `city`：城市
    - `theft_cases`：竊盜發生件數
    - `traffic_accident_cases`：駕駛過失發生件數
    - `alcohol_drive_cases`：酒駕發生件數
    - `general_injury_cases`：一般傷害發生件數
    - `total_crime_exclude_traffic`：刑案總件數(不含駕駛過失)
    - `sexual_assault_cases`：刑案總件數(不含駕駛過失)
    - `violent_crime_cases`：暴力犯罪發生件數
    - `drug_cases`：毒品查獲件數
    - `pop`：人口
    - `station`：氣象測站
    - `sunshine_hours`：日照時數
    - `avg_humidity`：月平均相對濕度
    - `avg_temp`：月平均氣溫
    - `rainy_days`：月降水日數
    - `precipitation`：月降水量

In [1]:
import pandas as pd

## Change for Your Own Data

In [2]:
input_data_file = "/Users/windkuo1017/Desktop/NTU_local/fa-25-econ-5166-group-4/data/processed/merged_data.csv"

In [3]:
df = pd.read_csv(input_data_file)

### Sample

In [4]:
df.head(10)

,date,year_x,month_x,city,theft_cases,traffic_accident_cases,alcohol_drive_cases,general_injury_cases,total_crime_exclude_traffic,sexual_assault_cases,violent_crime_cases,drug_cases,pop,station,sunshine_hours,avg_humidity,avg_temp,rainy_days,precipitation
0,2011/10/1,2011,10,南投縣,187.0,13.0,122.0,26.0,570.0,11.0,12.0,96.0,523176.0,日月潭,123.3,84,20.9,10,56.0
1,2011/10/1,2011,10,嘉義市,134.0,6.0,72.0,11.0,371.0,3.0,4.0,43.0,271644.0,嘉義,166.5,81,24.9,5,25.8
2,2011/10/1,2011,10,基隆市,147.0,13.0,61.0,24.0,489.0,6.0,11.0,148.0,380501.0,基隆,24.4,79,23.8,21,473.2
3,2011/10/1,2011,10,宜蘭縣,135.0,29.0,104.0,19.0,425.0,10.0,3.0,50.0,459296.0,宜蘭,33.5,82,23.2,23,579.6
4,2011/10/1,2011,10,屏東縣,261.0,28.0,133.0,23.0,834.0,21.0,17.0,204.0,865515.0,恆春,154.2,74,26.3,9,190.2
5,2011/10/1,2011,10,新竹市,169.0,22.0,99.0,26.0,430.0,4.0,4.0,42.0,418927.0,新竹,156.6,78,24.5,9,48.0
6,2011/10/1,2011,10,澎湖縣,13.0,2.0,25.0,6.0,86.0,NaN,1.0,10.0,97007.0,澎湖,137.5,75,25.0,2,7.5
7,2011/10/1,2011,10,臺中市,958.0,9.0,258.0,65.0,2284.0,47.0,38.0,246.0,2661290.0,臺中,188.6,70,26.0,5,13.3
8,2011/10/1,2011,10,臺北市,888.0,191.0,387.0,249.0,3589.0,28.0,36.0,341.0,2643136.0,臺北,53.3,77,24.1,13,92.6
9,2011/10/1,2011,10,臺南市,885.0,113.0,344.0,79.0,2076.0,24.0,29.0,236.0,1876312.0,臺南,165.2,72,26.2,7,27.8

### Summary Stats

In [5]:
df.describe()

,year_x,month_x,theft_cases,traffic_accident_cases,alcohol_drive_cases,general_injury_cases,total_crime_exclude_traffic,sexual_assault_cases,violent_crime_cases,drug_cases,pop,sunshine_hours,avg_humidity,avg_temp,rainy_days,precipitation
count,3992.000000,3992.000000,3880.000000,3515.000000,3844.000000,3831.000000,3983.000000,3553.000000,3198.000000,3726.000000,3.815000e+03,3992.000000,3992.000000,3992.000000,3992.000000,3992.000000
mean,2013.136774,6.477204,468.146649,51.241536,157.216181,45.916732,1181.470249,14.260625,22.137586,151.185454,8.657494e+05,153.588803,77.556613,23.342310,10.379008,163.968036
std,6.547043,3.420644,814.147952,76.130871,175.795720,56.032782,1491.044515,13.098044,41.534868,156.436520,9.440371e+05,59.595561,5.608214,4.800089,5.837170,194.481405
min,2002.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,8.807000e+03,1.300000,57.000000,7.100000,1.000000,0.100000
25%,2008.000000,4.000000,56.000000,7.000000,32.000000,11.000000,263.500000,5.000000,3.000000,39.000000,2.410305e+05,108.375000,74.000000,19.600000,6.000000,30.875000
50%,2013.000000,6.000000,151.000000,18.000000,85.000000,23.000000,545.000000,9.000000,7.000000,85.000000,4.290180e+05,153.550000,77.000000,23.800000,10.000000,95.900000
75%,2019.000000,9.000000,455.250000,49.000000,228.000000,58.000000,1695.500000,20.000000,19.000000,230.000000,1.040278e+06,195.900000,81.000000,27.800000,15.000000,219.575000
max,2024.000000,12.000000,5079.000000,626.000000,1107.000000,325.000000,7339.000000,83.000000,335.000000,1080.000000,2.860601e+06,364.300000,97.000000,31.100000,30.000000,1600.500000

### Assertions

In [ ]:
# Write assertions here—conditions that should always hold in the data.
# Use them to demonstrate that you have carefully checked the data’s correctness.